blank_issues_enabled: true
contact_links:
  - name: Chanify Community Support
    url: https://github.com/chanify/chanify/discussions
    about: Please ask and answer questions here.
  - name: Chanify Security Bug Bounty
    url: https://github.com/chanify/chanify/discussions/new?category=security
    about: Please report security vulnerabilities here.