blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://github.com/chanify/chanify/discussions/categories/q-a
    about: Please ask and answer questions here.
  - name: New Features Discussions
    url: https://github.com/chanify/chanify/discussions/categories/ideas
    about: Please share ideas for new features
  - name: Security Bug Report
    url: https://github.com/chanify/chanify/discussions/new?category=security
    about: Please report security vulnerabilities here.