name: ci
on:
  push:
    branches: [ main, dev ]
  pull_request:
  release:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.0'
    - name: Code lint
      uses: golangci/golangci-lint-action@v2
    - name: Test
      run: |
        go get github.com/wadey/gocovmerge
        make test
    - name: Code coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.out
  build:
    if: github.event_name == 'push' || github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build dev image
        if: github.ref == 'refs/heads/dev'
        run: echo "DOCKER_TAGS=wizjin/chanify:dev" >> $GITHUB_ENV
      - name: Build main image
        if: github.ref == 'refs/heads/main'
        run: echo "DOCKER_TAGS=wizjin/chanify:latest" >> $GITHUB_ENV
      - name: Build release image
        if: github.event_name == 'release'
        run: echo "DOCKER_TAGS=wizjin/chanify:${GITHUB_REF#v}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKER_TAGS }}
          build-args: TAGS=${{ env.DOCKER_TAGS }}
